# Generated by Django 5.1 on 2024-09-18 15:16

import django.db.models.deletion
import users.models.client
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.client.avatar_upload_to)),
                ('display_name', models.CharField(blank=True, max_length=50, verbose_name='Display Name')),
                ('mobile_number', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('shipping_address', models.CharField(blank=True, help_text='Required when buying physical merchandise(s).', max_length=255, null=True, verbose_name='Shipping Address')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('is_sms_verified', models.BooleanField(default=False, help_text="For determining if client's mobile number is valid or not.", verbose_name='SMS Verified')),
                ('newsletter', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-created_at'],
            },
        ),
    ]
