# Generated by Django 5.1 on 2024-09-19 10:32

import django.db.models.deletion
import users.models.admin
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_number', models.CharField(editable=False, max_length=15, unique=True, verbose_name='Admin Number')),
                ('department', models.CharField(choices=[('sysadmin', 'System Administrator'), ('billing', 'Billing Administrator'), ('product_manager', 'Product Manager'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('support', 'Customer Support')], default='sysadmin', max_length=20, verbose_name='Department')),
                ('avatar', models.ImageField(blank=True, default=None, null=True, upload_to=users.models.admin.avatar_upload_to)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
                'ordering': ['-created_at'],
            },
        ),
    ]
