# Generated by Django 5.1 on 2024-09-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='client_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True, verbose_name='Client Number'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Admin Number'),
        ),
    ]
