# Generated by Django 5.1 on 2024-09-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_client_client_number_alter_admin_admin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='Client Number'),
        ),
    ]
