# Generated by Django 5.1 on 2024-09-23 13:36

import django.core.validators
import django.db.models.deletion
import shop.models.shop
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Shop ID')),
                ('description', models.TextField(blank=True, help_text='A brief description of the shop.', null=True)),
                ('follower_count', models.PositiveIntegerField(default=0, verbose_name='Store Follower Count')),
                ('legal_id', models.FileField(blank=True, help_text='Upload a legal ID for shop owner verification. (Allowed Types: ".pdf", ".jpg", ".jpeg", ".png")', null=True, upload_to=shop.models.shop.legal_id_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Legal ID')),
                ('verification_document', models.FileField(blank=True, help_text='Upload a PDF document for shop verification. (e.g., DTI Permit)', null=True, upload_to=shop.models.shop.document_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])], verbose_name='Verification Document')),
                ('is_active', models.BooleanField(default=False, help_text='Indicates whether the shop is verified and active.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified At')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='users.client', verbose_name='Shop Owner')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'ordering': ['-created_at', '-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_followed', models.DateTimeField(auto_now_add=True, verbose_name='Date Followed')),
                ('fk_client', models.ForeignKey(help_text='The client who follows the shop.', on_delete=django.db.models.deletion.CASCADE, related_name='shops_followed', to='users.client', verbose_name='Client')),
                ('fk_shop', models.ForeignKey(help_text='The shop being followed.', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='shop.shop', to_field='shop_id', verbose_name='Shop')),
            ],
            options={
                'ordering': ['-date_followed'],
                'unique_together': {('fk_client', 'fk_shop')},
            },
        ),
    ]
