# Generated by Django 5.1 on 2024-09-27 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(help_text='The user who owns the shop.', on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, to_field='email', verbose_name='Shop Owner'),
        ),
        migrations.AddField(
            model_name='shopfollower',
            name='fk_shop',
            field=models.ForeignKey(help_text='The shop being followed.', on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='shop.shop', to_field='shop_id', verbose_name='Shop'),
        ),
        migrations.AddField(
            model_name='shopfollower',
            name='fk_user',
            field=models.ForeignKey(help_text='The user who follows the shop.', on_delete=django.db.models.deletion.CASCADE, related_name='shops_followed', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='shopfollower',
            unique_together={('fk_user', 'fk_shop')},
        ),
    ]
