# Generated by Django 5.1 on 2024-09-25 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_shop_follower_count'),
        ('users', '0003_client_client_number_alter_admin_admin_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='owner',
        ),
        migrations.AddField(
            model_name='shop',
            name='client',
            field=models.OneToOneField(help_text='Client who ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='users.client', to_field='client_number', verbose_name='Shop Owner'),
        ),
    ]
