# Generated by Django 5.1 on 2024-09-25 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_shop_owner_shop_client'),
        ('users', '0004_alter_client_client_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='client',
            field=models.OneToOneField(help_text='Client who ', on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='users.client', to_field='client_number', verbose_name='Shop Owner'),
        ),
    ]
